project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "JP Flores, PhD — CV"
  site-url: "https://jpflores-13.github.io/my-cv"
  navbar: false
  open-graph: true
  twitter-card: true
  image: "social-preview.png"

format:
  html:
    theme: none
    css: cv-styles.css
    toc: false
    self-contained: true
    page-layout: custom
